{
  LAZE-3D texture identifiers
}

TexBricks: GLUInt;
TexCompass: GLUInt;
TexCompassWorld: GLUInt;
TexConcrete: GLUInt;
TexConcreteRoof: GLUInt;
TexCroa: GLUInt;
TexCursor: GLUInt;
TexDiamond: GLUInt;
TexDirt: GLUInt;
TexDoor: GLUInt;
TexDoorblur: GLUInt;
TexEBD: Array[0..2] of GLUInt;
TexEBDShadow: GLUInt;
TexFacade: GLUInt;
TexFloor: GLUInt;
TexGlyphs: GLUInt;
TexHbd: GLUInt;
TexKey: GLUInt;
TexKoluplyk: GLUInt;
TexLamp: GLUInt;
TexLight: GLUInt;
TexMap: GLUInt;
TexMetal: GLUInt;
TexMetalFloor: GLUInt;
TexMetalRoof: GLUInt;
TexMotrya: GLUInt;
TexNoise: GLUInt;
TexPaper: GLUInt;
TexPipe: GLUInt;
TexPlanks: GLUInt;
TexPlaster: GLUInt;
TexRain: GLUInt;
TexRoof: GLUInt;
TexSigns1: GLUInt;
TexShadow: GLUInt;
TexSky: GLUInt;
TexTaburetka: GLUInt;
TexTileBig: GLUInt;
TexTilefloor: GLUInt;
TexTone: GLUInt;
TexTram: GLUInt;
TexTree: GLUInt;
TexTutorial: GLUInt;
TexTutorialJ: GLUInt;
TexVas: GLUInt;
TexVebra: GLUInt;
TexVignette: GLUInt;
TexVignetteRed: GLUInt;
TexWall: GLUInt;
TexWB: GLUInt;
TexWBBK: GLUInt;
TexWBBKP: GLUInt;
TexWBBK1: GLUInt;
TexWhitewall: GLUInt;

TexGlyph: Array[0..6] of GLUInt;

TexWmblykHappy: GLUInt;
TexWmblykNeutral: GLUInt;
TexWmblykJumpscare: GLUInt;
TexWmblykStr: GLUInt;
TexWmblykL1: GLUInt;
TexWmblykL2: GLUInt;
TexWmblykL3: GLUInt;
TexWmblykW1: GLUInt;
TexWmblykW2: GLUInt;

TexVirdyaBlink: GLUInt;
TexVirdyaDown: GLUInt;
TexVirdyaN: GLUInt;
TexVirdyaNeut: GLUInt;
TexVirdyaUp: GLUInt;

TexKubale: GLUInt;
TexKubaleInkblot: Array[0..8] of GLUInt;

TexFont: Array[0..40] of GLUInt;
